### ISSUE TITLE
Wrong mixing name

### ISSUE THREAD

**Issue by TheButterbrotMan** [Pale-Champion-Atom596/DiscsPlus#3]
https://i.imgur.com/Bx9TYAQ.png

**Comment by cmod31** [comment]
but what does it mean? is it a incompatible mod when yes wich is it?

**Comment by cmod31** [comment]
FOUND IT its incompatible with `croptopia-chocolaterie-0.5.jar`

**Comment by TheButterbrotMan** [comment]
lol, how did you? i was unable to do so

**Comment by cmod31** [comment]
i googled cocoa mod like it was called in the crash it showed up another mod with chocolate but this was the only chocolate mod in my mods folder so i just deleted it and it worked

**Comment by cmod31** [comment]
I'm btw using this for extra discs in a custom resourcepack maybe i'll just fork it when i don't get dmca for the music

**Comment by cmod31** [comment]
same with `RuntimeException: Non-unique Mixin config name modid.mixins.json used by the mods discsplus and zzz`

**Comment by Pale-Champion-Atom596** [comment]
Hey, sorry for the slow reply. I fixed this issue in the latest versions of the mod.
